# Generated by Django 6.0.6 on 2026-06-07 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value_type', models.CharField(default='STRING', max_length=50)),
                ('value_string', models.TextField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('SYSTEM', 'System Level'), ('COMPANY', 'Company Level'), ('FEATURE_FLAG', 'Feature Flag'), ('ENV_VAR', 'Environment Variable')], default='SYSTEM', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
