# Generated by Django 6.0.6 on 2026-06-07 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image File'), ('VIDEO', 'Video File'), ('DOCUMENT', 'Word/Excel Document'), ('OTHER', 'Other')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('object_id', models.UUIDField()),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
